package com.tutorialspoint.hibernate.pojo;

import java.util.Set;

// Generated 21 d�c. 2014 12:27:20 by Hibernate Tools 4.0.0

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;
	private Integer salary;
	private Address address;
	private Account account;
	private Set<Certificate> certificates;
	private Set<Meeting> meetings;

	public Employee() {
	}		
	
	public Employee(String firstname, String lastname, Integer salary, Address address, Account account, Set<Certificate> certificates, Set<Meeting> meetings) {
		super();
		this.firstname = firstname;
		this.lastname = lastname;
		this.salary = salary;
		this.address = address;
		this.account = account;
		this.setCertificates(certificates);
		this.meetings = meetings;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Integer getSalary() {
		return salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Set<Certificate> getCertificates() {
		return certificates;
	}

	public void setCertificates(Set<Certificate> certificates) {
		this.certificates = certificates;
	}

	public Set<Meeting> getMeetings() {
		return meetings;
	}

	public void setMeetings(Set<Meeting> meetings) {
		this.meetings = meetings;
	}
		
}
